name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: brew style
        run: brew style ${{ steps.set-up-homebrew.outputs.tap-name }}

      - name: brew audit
        run: brew audit --strict ${{ steps.set-up-homebrew.outputs.tap-name }}/gset

      - name: brew install from source
        run: brew install --build-from-source ${{ steps.set-up-homebrew.outputs.tap-name }}/gset

      - name: brew test
        run: brew test ${{ steps.set-up-homebrew.outputs.tap-name }}/gset
